version: "3.8"

services:
  backend:
    build: ./evolva-core
    ports:
      - "${PORT_BACKEND:-8080}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - evolva-net

  frontend:
    build: ./evolva-panel
    ports:
      - "${PORT_FRONTEND:-3000}:80"
    restart: unless-stopped
    networks:
      - evolva-net

  db:
    image: postgres:15
    container_name: evolva-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${PORT_DB:-5432}:5432"
    networks:
      - evolva-net

volumes:
  pgdata:

networks:
  evolva-net:
    driver: bridge
